### ISSUE TITLE
Use steipete/Aspects to auto inject properties non-intrusively

### ISSUE THREAD

**Issue by aceontech** [appfoundry/Reliant#11]
Not sure if this has been done before, but I tested out using @steipete's Aspects to set up automatic property injection without imposing boilerplate `[self ocsInject]`s all over the place (and it works rather nicely). It also furthers our goal of being non-intrusive - regardless of view life cycle particulars.

E.g.: set up a hook in the `-viewDidLoad` method of any `UIViewController` which calls `-ocsInject` before control is handed back to the original `-viewDidLoad` implementation.

```objc
NSError *error;
[UIViewController aspect_hookSelector:@selector(viewDidLoad)
                          withOptions:AspectPositionBefore
                           usingBlock:^(id <AspectInfo> aspectInfo) {
                               UIViewController *instance = (UIViewController *) aspectInfo.instance;
                               [instance ocsInject];
                           }
                                error:&error];
```

I think we could (optionally) make this part of the the root bootstrapping process. I'm working on an example to demonstrate this.

Open to suggestions, improvements and/or critique.

**Comment by mikeseghers** [comment]
I love this aspect approach. It would mean Reliant becomes dependant on the Aspects library if we would make this available out-of-the-box. I've been keeping away from including transitive dependencies...

If we would include the dependency, this is something we can include in the first bootstrap process of reliant. Another remark: since this would be a "before" aspect, we need to make sure reliant doesn't break the viewcontroller lifecycle (I don't think it will, but just in case..., we already have some excluded properties in place, exactly to remove these kind of issues).

**Comment by aceontech** [comment]
There _are_ potential issues with contexts being bootstrapped after the inject hook has run, i.e. in a `-viewDidLoad`. This could be solved by imposing a more formal bootstrapping moment in the lifecycle, instead of letting the application code decide this arbitrarily (and usually end up in  `-viewDidLoad` or similar. 

E.g.: We could introduce some kind of context bootstrap registry which the inject hook would inspect, and bootstrap any contexts and sub-contexts in sequence, before injecting. Introducing a more formal lifecycle around bootstrapping would also remove the ambiguity that currently exists with Storyboards, and might improve users' general understand of what happens when.

Why not provide one bootstrap point (e.g. in app delegate) which outlines all of the contexts which need to be constructed throughout the application, identified by their context-holding class name. Reliant could then (using aspect hooks), bootstrap contexts just in time as the context-holding classes are brought to life (right before a `-viewDidLoad` or similar). 

Here's a hypothetical code example of such a mythical beast:

```objc
[Reliant addContextBootstrapConfigurationFromClass:[GeneralAppConfiguration class]];
[Reliant addContextBootstrapConfigurationFromClass:[NestedConfiguration class] parentContextClass:[GeneralAppConfiguration class]];
```
As stated above, while the app is running, Reliant would use hooks to bootstrap and inject contexts as necessary and no other bootstrap/inject calls would be littered around the application code.

P.S.: Just spewing ideas. None of these ideas might be any good, or feasible to implement. Hope it makes sense :)

**Comment by mikeseghers** [comment]
Can we close this one, or do we need further discussion?

**Comment by aceontech** [comment]
I would also just close it for now.
