### ISSUE TITLE
Suggestion: Use class instead of string for parentContext reference?

### ISSUE THREAD

**Issue by aceontech** [appfoundry/Reliant#14]
See [OCSConfiguratorFromClass.h:27](https://github.com/appfoundry/Reliant/blob/c48c7923032482ed8aec18175d5b73a81de842ca/Reliant/Classes/Configurator/OCSConfiguratorFromClass.h#L27)

In order to limit typos, could we change this to `-parentContextClass` instead? The implementation could still derive a string using `NSStringFromClass`.

**Comment by mikeseghers** [comment]
Should we include this in issue #10 ?

**Comment by mikeseghers** [comment]
Can we close this one?

**Comment by aceontech** [comment]
Yeah, not important.
