### ISSUE TITLE
Manager not injected in initialiser in other manager

### ISSUE THREAD

**Issue by jaernouts** [appfoundry/Reliant#19]
Hi guys!

I discovered an issue (well, at least I think it's an issue, maybe I'm doing something wrong), when you use a manager within another manager. I'll show you a small example:

I have a 'UserManager' which uses a 'PreferencesManager' in his init method. As the documentation says, the injection should be done automatically, but my PreferencesManager keeps being 'nil'. When I do '[self ocsInject]', it's working correctly - but I thought I didn't have to do that?

So, wrong, not working - self.preferencesManger is still nil: 
```
- (instancetype)init {
    self = [super init];
    if (self) {
        _primaryMsisdn = [self.preferencesManager objectForKey:PreferenceKeyPrimaryMsisdn];
    }

    return self;
}
```

Good, self.preferencesManager is injected properly:
```
- (instancetype)init {
    self = [super init];
    if (self) {
        [self ocsInject];
        
        _primaryMsisdn = [self.preferencesManager objectForKey:PreferenceKeyPrimaryMsisdn];
    }

    return self;
}
```

It's a good workaround for now, but I thought I didn't need to do the '[self ocsInject]' within already injected managers...?

Regards!

**Comment by bartvandeweerdt** [comment]
Hi Jens! Is UserManager itself instantiated by Reliant?

**Comment by jaernouts** [comment]
Hi Bart! Yes, it is, here's a snippet of my AppConfiguration:

```
- (id <IPreferencesManager>)createSingletonPreferencesManager {
    return [[PreferencesManager alloc] init];
}

- (id <IUserManager>)createSingletonUserManager {
    return [[UserManager alloc] init];
}
```

Regards!

**Comment by bartvandeweerdt** [comment]
Actually, come to think of it, I don't think your preferencesManager property has been set (injected) yet because you are still inside the constructor of your 'to-inject' class. 
To achieve what you are trying to do, I'd recommend using constructor injection. In other words:

```
- (instancetype)initWithPrefManager:(id < IPreferencesManager >)pm {
    self = [super init];
    if (self) {   
        _preferenceManager = pm; //this can be a (private) ivar
        _primaryMsisdn = [_preferencesManager objectForKey:PreferenceKeyPrimaryMsisdn];
    }
    return self;
}
```

This is also nice for injecting a mock IPreferenceManager when your are testing this code.

**Comment by mikeseghers** [comment]
Indeed, we can only inject via properties after initialization. Property injection is nice for objects that are not created by reliant itself, but you should probably prefer initializer/constructor injection as @bartvandeweerdt explained.

**Comment by jaernouts** [comment]
Ok,clear explanation! I will do it like that! Thx for the explanation!
